--rollback
DROP SEQUENCE WRITER.INFO_SEQUENCE;
DROP SEQUENCE WRITER.BOOK_SEQUENCE;

DROP TABLE WRITER.BOOK;
DROP TABLE WRITER.INFO;


select WRITER.INFO_SEQUENCE.nextval
from dual;

REVOKE CREATE DATABASE LINK FROM WRITER;
REVOKE ALTER SESSION FROM WRITER;
REVOKE CREATE VIEW FROM WRITER;
REVOKE UNLIMITED TABLESPACE FROM WRITER;
REVOKE CREATE SESSION FROM WRITER;
REVOKE CREATE SEQUENCE FROM WRITER;
REVOKE CREATE SYNONYM FROM WRITER;
REVOKE CREATE ANY INDEX FROM WRITER;
REVOKE RESOURCE FROM WRITER;